#' Simulate VIC
#' @param days_to_simulate The number of days to simulate.
#' @param PolicyPars A list generated by \code{set_policypars()}, the
#' policy parameters.
#' @param EpiPars The epidemiological parameters. See \code{set_epipars()}.
#'
#' @param showProgress,nThread Not yet used.
#'
#'
#' @export


simulate_vic <- function(days_to_simulate = 28,
                         PolicyPars = set_policypars(),
                         EpiPars = set_epipars(),
                         showProgress = getOption("caemovir.showProgress", 1L),
                         nThread = getOption("caemovir.nThread", 1L)) {
  myaus <- default_vic()
  stopifnot(hasNames(myaus, "hid", "wid", "Age"))
  hid <- myaus$hid
  wid <- myaus$wid
  Age <- myaus$Age
  Policy <- NULL
  Returner <- 10L
  .Call("C_caemovir",
        days_to_simulate,
        hid,
        wid,
        Age,
        Policy,
        EpiPars,
        Returner,
        PACKAGE = packageName())
}


simulate_vicR <- function(days_to_simulate = 28,
                          Victoria = NULL,
                          InitialStatus = NULL) {
  if (is.null(Victoria)) {
    Victoria <- default_vic()
  }

}

test_roundtrip_H2U2H <- function(x) {
  stopifnot(is.integer(x), length(x) == 1L, !anyNA(x))
  .Call("C_test_roundtrip_H2U2H", x, PACKAGE = packageName())
}



